pipeline {
    agent any

    tools {
        maven 'Maven 3.9.9'
    }

    environment {
        APP_NAME = "employee_service"
        RELEASE = "latest"
        DOCKER_USER = "oumaimaboughdad"
        DOCKER_PASS = credentials('docker-credentials')
        IMAGE_NAME = "${DOCKER_USER}/${APP_NAME}"
        IMAGE_TAG = "latest"
    }

    stages {
        stage('Checkout SCM') {
            steps {
                checkout scm
            }
        }

        stage('Build') {
            steps {
                echo 'Building the employee microservice ......'
                dir('Microservices/employee_service') {
                    sh 'mvn clean package -DskipTests'
                }
            }
        }

        stage('SonarQube Analysis') {
            steps {
                script {
                    withSonarQubeEnv(credentialsId: 'sonar-token-for-jenkins') {
                        dir('Microservices/employee_service') {
                            sh 'mvn sonar:sonar'
                        }
                    }
                }
            }
        }

        stage('Build & Push Docker Image') {
            steps {
                script {
                    withCredentials([usernamePassword(credentialsId: 'docker-credentials', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
                        dir('Microservices/employee_service') {
                            sh '''
                                echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
                                docker build -t ${IMAGE_NAME}:${IMAGE_TAG} -f Dockerfile .
                                docker push ${IMAGE_NAME}:${IMAGE_TAG}
                            '''
                        }
                    }
                }
            }
        }
    }
}
