pipeline {
    agent any

    tools {
        nodejs 'NodeJS 18' // Ensure Node.js version is correctly installed on the agent
    }

    environment {
        APP_NAME = "front-app"
        DOCKER_USER = "oumaimaboughdad"
        DOCKER_PASS = credentials('docker-credentials') // Reference to Jenkins credential ID
        IMAGE_NAME = "${DOCKER_USER}/${APP_NAME}"
        IMAGE_TAG = "latest"
    }

    stages {
        stage('Checkout SCM') {
            steps {
                checkout scm
            }
        }

        stage('Install Dependencies') {
            steps {
                dir('frontend/front') { // Navigate to the correct directory
                    sh 'npm install'
                }
            }
        }

        stage('Build') {
            steps {
                dir('frontend/front') {
                    sh 'ng build --configuration production'
                }
            }
        }

        stage('Test') {
            steps {
                dir('frontend/front') {
                    sh 'ng test --watch=false --code-coverage' // Run unit tests with code coverage
                }
            }
        }

        stage('SonarQube Analysis') {
            steps {
                withSonarQubeEnv('SonarQube') { // Ensure SonarQube server is configured in Jenkins
                    dir('frontend/front') {
                        sh 'npm run sonar' // Ensure 'sonar' script is defined in package.json
                    }
                }
            }
        }

        stage('Cleanup Docker Image') {
            steps {
                script {
                    sh """
                        docker logout
                        docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
                        docker rmi -f ${IMAGE_NAME}:${IMAGE_TAG} || true
                    """
                }
            }
        }

        stage('Build & Push Docker Image') {
            steps {
                script {
                    dir('frontend/front') { // Change to the directory containing the Dockerfile
                        docker.withRegistry('https://registry.hub.docker.com', env.DOCKER_PASS) { // Use Docker Hub registry
                            // Build Docker image
                            docker_image = docker.build("${IMAGE_NAME}")
                            
                            // Push Docker image with the specified tag and 'latest'
                            docker_image.push("${IMAGE_TAG}")
                            docker_image.push('latest')
                        }
                    }
                }
            }
        }
    }

    post {
        success {
            echo 'Pipeline completed successfully.'
        }
        failure {
            echo 'Pipeline failed. Please check the logs.'
        }
    }
}
