pipeline {
    agent { label 'jenkins-agent' }

    tools {
        maven 'Maven 3.9.9'
    }

    environment {
        APP_NAME = "eureka_main"
        RELEASE = "latest"
        DOCKER_USER = "oumaimaboughdad"
        DOCKER_PASS = 'token-for-the-jenkins'
        IMAGE_NAME = "${DOCKER_USER}/${APP_NAME}"
        IMAGE_TAG = "latest"
    }

    stages {
         // Cleanup Docker Image Stage
        stage('Cleanup Docker Image') {
            steps {
                script {
                    // Remove the Docker image if it exists
                    sh(script: """
                        if docker images -q ${IMAGE_NAME}:${IMAGE_TAG} 2>/dev/null; then
                            docker rmi -f ${IMAGE_NAME}:${IMAGE_TAG}
                        fi
                    """)
                }
            }
        }

        stage('Checkout SCM') {
            steps {
                checkout scm
            }
        }

        stage('Build') {
            steps {
                echo 'Building the eureka-service microservice ......'
                dir('Microservices/eureka_main') {
                    sh 'mvn clean package -DskipTests'
                }
            }
        }

        stage('SonarQube Analysis') {
            steps {
                script {
                    withSonarQubeEnv(credentialsId: 'sonar-token-for-jenkins') {
                        dir('Microservices/eureka_main') {
                            sh 'mvn sonar:sonar'
                        }
                    }
                }
            }
        }

        stage('Build & Push Docker Image') {
            steps {
                script {
                    dir('Microservices/eureka_main') {
                        docker.withRegistry('', DOCKER_PASS) {
                            docker_image = docker.build("${IMAGE_NAME}")
                            docker_image.push("${IMAGE_TAG}")
                            docker_image.push('latest')
                        }
                    }
                }
            }
        }
    }
}
