pipeline {
    agent any

    tools {
        maven 'Maven 3.9.9' // Ensure this matches the Maven version configured in Jenkins
    }

    stages {
        stage('Checkout SCM') {
            steps {
                checkout scm
            }
        }

        stage('Build') {
            steps {
                echo 'Building the eureka microservice ......  '
                dir('Microservices/eureka_main ') { // Change to the directory containing pom.xml
                    sh 'mvn clean package'
                }
            }
        }
    }
}