apiVersion: apps/v1
kind: Deployment
metadata:
  name: compte-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: compte-service
  template:
    metadata:
      labels:
        app: compte-service
    spec:
      containers:
        - name: compte-service
          image: oumaimaboughdad/compte-service:latest
          ports:
            - containerPort: 8086
          envFrom:
            - secretRef:
                name: compte-service-secrets