pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                echo 'Building the microservice...'
                sh 'mvn clean package'  // Use Maven Wrapper for Windows
            }
        }
    }
}