pipeline {
    agent any

    tools {
        maven 'Maven 3.9.9'
        dockerTool 'Docker'
    }

    environment {
        DOCKER_HUB_TOKEN = credentials('docker-hub-token')
        DOCKER_IMAGE_NAME = 'oumaimaboughdad/api-gateway'
    }

    stages {
        stage('Checkout SCM') {
            steps {
                checkout scm
            }
        }

        stage('Build') {
            steps {
                echo 'Building the microservice...'
                dir('Microservices/api-gateway') {
                    sh 'mvn clean package -DskipTests'
                }
            }
        }

        stage('SonarQube Analysis') {
            steps {
                withSonarQubeEnv('Sonar-7') {
                    dir('Microservices/api-gateway') {
                        sh '''
                        mvn sonar:sonar \
                            -Dsonar.host.url=http://16.170.223.44:9000/ \
                            -Dsonar.login=squ_1ae4f5b6d10ad27965eb511624faa9f2da2dc9fc \
                            -Dsonar.projectKey=api-gateway
                        '''
                    }
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                echo 'Building Docker image...'
                script {
                    docker.build("${env.DOCKER_IMAGE_NAME}:latest", 'Microservices/api-gateway')
                }
            }
        }

        stage('Push Docker Image to Docker Hub') {
            steps {
                echo 'Pushing Docker image to Docker Hub...'
                script {
                    docker.withRegistry('https://registry.hub.docker.com', 'docker') {
                        docker.image("${env.DOCKER_IMAGE_NAME}:latest").push()
                    }
                }
            }
        }
    }
}