pipeline {
    agent any

    tools {
        maven 'Maven 3.9.9' // Ensure this matches the Maven version configured in Jenkins
    }

    stages {
        stage('Checkout SCM') {
            steps {
                checkout scm
            }
        }

        stage('Build') {
            steps {
                echo 'Building the transaction microservice ......  '
                dir('Microservices/transaction-service') { // Change to the directory containing pom.xml
                    sh 'mvn clean package -DskipTests'
                }
            }
        }

         stage('SonarQube Analysis') {
                    steps {
                        withSonarQubeEnv('SonarQube') { // Use the name configured in Jenkins
                            sh 'mvn sonar:sonar -Dsonar.host.url=http://http://51.20.87.109:9000 -Dsonar.login=Sqa_1edd27e4ad72c8e103459f7a0eab4c058d3345ac'
                        }
                    }
          }




    }
}