apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
data:
  application.yml: |
    server:
      port: 8080
    eureka:
      client:
        serviceUrl:
          defaultZone: http://eureka-main:8761/eureka