pipeline {
    agent { label 'jenkins-agent' }

    tools {
        maven 'Maven 3.9.9'
    }

    environment {
        APP_NAME = "Credit_Microservice"
        RELEASE = "latest"
        DOCKER_USER = "oumaimaboughdad"
        DOCKER_PASS = 'token-for-the-jenkins'
        IMAGE_NAME = "${DOCKER_USER}/${APP_NAME}"
        IMAGE_TAG = "latest"
    }

    stages {
        stage('Checkout SCM') {
            steps {
                checkout scm
            }
        }

        stage('Build') {
            steps {
                echo 'Building the Credit_Microservice microservice ......'
                dir('Microservices/Credit_Microservice') {
                    sh 'mvn clean package -DskipTests'
                }
            }
        }

        stage('SonarQube Analysis') {
            steps {
                script {
                    withSonarQubeEnv(credentialsId: 'sonar-token-for-jenkins') {
                        dir('Microservices/Credit_Microservice') {
                            sh 'mvn sonar:sonar'
                        }
                    }
                }
            }
        }

        stage('Build & Push Docker Image') {
            steps {
                script {
                    dir('Microservices/Credit_Microservice') {
                        docker.withRegistry('', DOCKER_PASS) {
                            docker_image = docker.build("${IMAGE_NAME}")
                            docker_image.push("${IMAGE_TAG}")
                            docker_image.push('latest')
                        }
                    }
                }
            }
        }
    }
}