apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-main
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka-main
  template:
    metadata:
      labels:
        app: eureka-main
    spec:
      containers:
        - name: eureka-main
          image: your-docker-repo/eureka-main:latest
          ports:
            - containerPort: 8761